import { join } from 'node:path';
import { app, nativeImage, type NativeImage } from 'electron';
import type { AppState } from '@shared/types';

/**
 * Tray icons live in resources/icons and are generated by
 * `scripts/generate-icons.mjs` (`npm run icons`). Two variants exist per
 * state:
 *
 *   tray-<state>.png / @2x        monochrome black glyph → macOS *template*
 *                                 image (auto-inverts for dark menu bars)
 *   tray-<state>-color.png / @2x  brand roundel → Windows / Linux, where the
 *                                 taskbar may be light OR dark and template
 *                                 images are not supported.
 *
 * Electron resolves the `@2x` sibling automatically for HiDPI displays when
 * given the 1x path.
 *
 * In a packaged build the folder is copied by electron-builder's
 * `extraResources` (see electron-builder.yml) into `<app>/resources/icons`.
 */
const iconRoot = app.isPackaged
  ? join(process.resourcesPath, 'icons')
  : join(__dirname, '../../resources/icons');

const stateFor: Record<AppState, 'idle' | 'recording' | 'processing'> = {
  idle: 'idle',
  recording: 'recording',
  processing: 'processing',
  injecting: 'processing',
  success: 'idle',
  error: 'idle'
};

export function trayIconPath(
  state: AppState,
  platform: NodeJS.Platform = process.platform
): string {
  const variant = platform === 'darwin' ? '' : '-color';
  return join(iconRoot, `tray-${stateFor[state] ?? 'idle'}${variant}.png`);
}

export function trayIcon(state: AppState): NativeImage {
  const image = nativeImage.createFromPath(trayIconPath(state));
  // On macOS, mark as template so it inverts with light/dark menu bar.
  if (process.platform === 'darwin') {
    image.setTemplateImage(true);
  }
  return image;
}
