import { join } from 'node:path';
import { nativeImage, type NativeImage } from 'electron';
import type { AppState } from '@shared/types';
import { iconsDir } from '@main/utils/paths';
import { logger } from '@main/utils/logger';

/**
 * Tray icons live in resources/icons and are generated by
 * `scripts/generate-icons.mjs` (`npm run icons`). Two variants exist per
 * state:
 *
 *   tray-<state>.png / @2x        monochrome black glyph → macOS *template*
 *                                 image (auto-inverts for dark menu bars)
 *   tray-<state>-color.png / @2x  brand roundel → Windows / Linux, where the
 *                                 taskbar may be light OR dark and template
 *                                 images are not supported.
 *
 * Electron resolves the `@2x` sibling automatically for HiDPI displays when
 * given the 1x path.
 *
 * Location (dev vs packaged) is resolved by `iconsDir()`.
 */

const stateFor: Record<AppState, 'idle' | 'recording' | 'processing'> = {
  idle: 'idle',
  recording: 'recording',
  processing: 'processing',
  injecting: 'processing',
  success: 'idle',
  error: 'idle'
};

export function trayIconPath(
  state: AppState,
  platform: NodeJS.Platform = process.platform
): string {
  const variant = platform === 'darwin' ? '' : '-color';
  return join(iconsDir(), `tray-${stateFor[state] ?? 'idle'}${variant}.png`);
}

export function trayIcon(state: AppState): NativeImage {
  const path = trayIconPath(state);
  const image = nativeImage.createFromPath(path);
  if (image.isEmpty()) {
    // An empty image renders as a blank tray slot (only the tooltip shows) —
    // log loudly so a packaging regression is obvious in app.log.
    logger.error('tray icon failed to load', { path });
  }
  // On macOS, mark as template so it inverts with light/dark menu bar.
  if (process.platform === 'darwin') {
    image.setTemplateImage(true);
  }
  return image;
}
